services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup true --interval 7200

  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    hostname: tailscale
    environment:
      - TS_AUTHKEY=/run/secrets/secret
      - TS_EXTRA_ARGS=--accept-routes=true
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ROUTES=10.0.0.0/24
      - TS_HOSTNAME=heimdall
    volumes:
      - ${PWD}/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    restart: unless-stopped
    secrets:
      - secret

  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ${PWD}/homer:/www/assets
    ports:
      - 8080:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
      - IPV6_DISABLE=1
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ${PWD}/uptime-kuma-data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped

secrets:
  secret:
    file: ./secret
