- link:
    $HOME/.config/hypr/hyprland.conf: configs/hyprland/hyprland.conf
    $HOME/.config/hypr/keybindings.conf: configs/hyprland/keybindings.conf
    $HOME/.config/hypr/monitors.conf: configs/hyprland/monitors.conf
    $HOME/.config/hypr/userprefs.conf: configs/hyprland/userprefs.conf
