- link:
    $HOME/git/IdeaProjects/.devcontainer/devcontainer.json: configs/java/.devcontainer/devcontainer.json
    $HOME/git/IdeaProjects/.devcontainer/docker-compose.yml: configs/java/.devcontainer/docker-compose.yml
