- defaults:
    link:
      relink: true
      create: true
      force: true

- clean:
    $HOME/:
      force: true
    $HOME/.config:
      recursive: true

- shell:
    - [git submodule update --init --recursive, Installing submodules]
